name: build

on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js for semantic-release
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create semantic-release
        id: version
        run: |
          npm ci
          npm_config_yes=true npx semantic-release
