name: build

on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm ci

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Create build
        run: |
          npm run build

  semantic-release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Create semantic-release
        run: |
          npm_config_yes=true npx semantic-release
