name: test

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Pack chrome extension
        run: |
          cd dist && zip -r -FS ../Package.zip *

      - name: Drop chrome artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "Chrome Artifacts"
          path: ./dist
          if-no-files-found: error

      - name: Create firefox build
        run: |
          rm Package.zip
          ./firefoxfy.sh

      - name: Pack firefox extension
        run: |
          cd dist && zip -r -FS ../Package.zip *

      - name: Drop firefox artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "Firefox Artifacts"
          path: ./dist
          if-no-files-found: error
