name: test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js for build
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Test code
        run: |
          npm ci
          npm run test
